local testUi
AddEvent("OnPlayerSpawn", function()
    testUi = CreateWebUI(0.0, 0.0, 0.0, 0.0, 5, 60)
	LoadWebFile(testUi, "http://asset/onset_react_demo/onset_react_boilerplates/react_ts_webpack/build/index.html")
	SetWebAlignment(testUi, 0.0, 0.0)
	SetWebAnchors(testUi, 0.0, 0.0, 1.0, 1.0)
    SetWebVisibility(testUi, WEB_VISIBLE)
    AddPlayerChat("Spawning react UI")
    SetInputMode(INPUT_UI)    
    
    CreateTimer(function()
        AddPlayerChat("Incrementing")
        name = GetPlayerName()
        ExecuteWebJS(testUi, "incrementCounter('"..name.."')")
    end, 1000)
end)
